### ISSUE TITLE
Leaky RNN

### ISSUE THREAD

**Issue by atremblay** [atremblay/chronoRNN#6]
Need to implement the leaky RNN (equation 5)  with
h𝑡+1 =𝛼tanh(𝑊𝑥𝑥𝑡 +𝑊hh𝑡 +𝑏)+(1−𝛼)h𝑡

This could probably be directly done in the Rnn class that we already have and use a different argument to turn on the leakage.

**Comment by JulesGM** [comment]
this now works. someone else can test it if they desire.
https://github.com/atremblay/chronoRNN/blob/master/models/rnn.py
