### ISSUE TITLE
Add bias initialization to 1 for the LSTM.

### ISSUE THREAD

**Issue by atremblay** [atremblay/chronoRNN#7]
For the tests the authors are using an LSTM with the biases initialized to 1. Currently we don't support this, only the chrono initialization.
So either a new class for this or add a switch to ChronoLSTM to initialize the bias to 1, up to the person working on this issue.

**Comment by JulesGM** [comment]
Closed with 72075ee50c0c37aa9560d451eecfc27c65a1d6c3
